CREATE TABLE PLANO_DE_SAUDE (
    COD INT,
    NOME VARCHAR(50) NOT NULL,
    PRIMARY KEY (COD)
);
CREATE TABLE ENDERECO (
    COD INT,
    CIDADE VARCHAR2(20)NOT NULL,
    ESTADO VARCHAR2(20)NOT NULL,
    BAIRRO VARCHAR2(30)NOT NULL,
    RUA VARCHAR2(30)NOT NULL,
    PRIMARY KEY (COD)   
);
CREATE TABLE PACIENTE (
    CPF VARCHAR2(15),
    NOME VARCHAR(50) NOT NULL,
    IDADE INT NOT NULL,
    SEXO VARCHAR2(50),
    PLANO_DE_SAUDE_COD INT,
    ENDERECO_COD INT NOT NULL,
    PRIMARY KEY (CPF),
    FOREIGN KEY (PLANO_DE_SAUDE_COD) REFERENCES PLANO_DE_SAUDE (COD),
    FOREIGN KEY (ENDERECO_COD) REFERENCES ENDERECO (COD)
);

CREATE TABLE MEDICO (
    CRM VARCHAR2(16),
    NOME VARCHAR(50) NOT NULL,
    PRIMARY KEY (CRM)
);
CREATE TABLE ESPECIALIZACAO (
    ESPECIALIZACAO INT,
    MEDICO_CRM VARCHAR2(16) NOT NULL,
    PRIMARY KEY (ESPECIALIZACAO, MEDICO_CRM),
    FOREIGN KEY (MEDICO_CRM) REFERENCES MEDICO (CRM)
);
CREATE TABLE DEPARTAMENTO (
    COD INT,
    NOME VARCHAR2(16) NOT NULL,
    PRIMARY KEY (COD)
);

CREATE TABLE FUNCIONARIO (
    CPF VARCHAR2(15),
    NOME VARCHAR(50) NOT NULL,
    IDADE INT NOT NULL,
    SEXO VARCHAR2(50),
    PRIMARY KEY (CPF)
);
CREATE TABLE ADMINISTRATIVO (
    CPF_FUNCIONARIO VARCHAR2(15) NOT NULL,
    QTD_VENDIDA INT,
    PRIMARY KEY (CPF_FUNCIONARIO),
    FOREIGN KEY (CPF_FUNCIONARIO) REFERENCES FUNCIONARIO (CPF)
);
CREATE TABLE TECNICO (
    CPF_FUNCIONARIO VARCHAR2(15) NOT NULL,
    FORMACAO VARCHAR2(15) NOT NULL,
    COD_DEPARTAMENTO INT NOT NULL,
    PRIMARY KEY (CPF_FUNCIONARIO),
    FOREIGN KEY (CPF_FUNCIONARIO) REFERENCES FUNCIONARIO (CPF),
    FOREIGN KEY (COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO (COD)
);
CREATE TABLE EXAME (
    COD INT,
    NOME VARCHAR2(15) NOT NULL,
    PRECO INT NOT NULL,
    CPF_PACIENTE VARCHAR2(15) NOT NULL,
    CRM_MEDICO VARCHAR2(16),
    PRIMARY KEY (COD),
    FOREIGN KEY (CPF_PACIENTE) REFERENCES PACIENTE (CPF),
    FOREIGN KEY (CRM_MEDICO) REFERENCES MEDICO (CRM)
);
CREATE TABLE VENDA (
    COD INT,
    DATA DATE NOT NULL,
    COD_EXAME INT NOT NULL,
    CPF_ADMINISTRATIVO VARCHAR2(15) NOT NULL,
    CPF_TECNICO VARCHAR2(15) NOT NULL,
    PRIMARY KEY (COD_EXAME,CPF_TECNICO),
    FOREIGN KEY (CPF_TECNICO) REFERENCES TECNICO (CPF_FUNCIONARIO),
    FOREIGN KEY (CPF_ADMINISTRATIVO) REFERENCES ADMINISTRATIVO (CPF_FUNCIONARIO),
    FOREIGN KEY (COD_EXAME) REFERENCES EXAME (COD)
);