CREATE SEQUENCE SEQ_PLANO
 START WITH     1
 INCREMENT BY   1
 MAXVALUE 20
 NOCACHE
 NOCYCLE;
 
CREATE SEQUENCE SEQ_ENDERECO
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
  
CREATE SEQUENCE SEQ_PACIENTE
 START WITH     220330440
 INCREMENT BY   100
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE SEQ_MEDICO
 START WITH     0200
 INCREMENT BY   20
 NOCACHE
 NOCYCLE;
CREATE SEQUENCE SEQ_EXAME
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
-- 20 tuplas de departamento + sequence

CREATE SEQUENCE SEQ_DEPARTAMENTO
 START WITH     22
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE SEQ_FUNCIONARIO
 START WITH     420330440
 INCREMENT BY   100
 NOCACHE
 NOCYCLE;
 
CREATE SEQUENCE SEQ_FUNC_ADM
 START WITH     420330440
 INCREMENT BY   100
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE SEQ_FUNC_TEC
 START WITH 420332440
 INCREMENT BY 100
 NOCACHE
 NOCYCLE;

INSERT INTO DEPARTAMENTO VALUES(SEQ_DEPARTAMENTO.NEXTVAL,'T.I');
INSERT INTO DEPARTAMENTO VALUES(SEQ_DEPARTAMENTO.NEXTVAL,'BIOQUIMICA');
INSERT INTO DEPARTAMENTO VALUES(SEQ_DEPARTAMENTO.NEXTVAL,'HEMATOLOGIA');
INSERT INTO DEPARTAMENTO VALUES(SEQ_DEPARTAMENTO.NEXTVAL,'IMUNOLOGIA');
INSERT INTO DEPARTAMENTO VALUES(SEQ_DEPARTAMENTO.NEXTVAL,'MICROBIOLOGIA');
INSERT INTO DEPARTAMENTO VALUES(SEQ_DEPARTAMENTO.NEXTVAL,'COLETA E ORGANIZAÇÃO DE MATERIAL');
INSERT INTO DEPARTAMENTO VALUES(SEQ_DEPARTAMENTO.NEXTVAL,'lIMPEZA');
INSERT INTO DEPARTAMENTO VALUES(SEQ_DEPARTAMENTO.NEXTVAL,'RECURSOS HUMANOS');
INSERT INTO DEPARTAMENTO VALUES(SEQ_DEPARTAMENTO.NEXTVAL,'TRANSPORTE');
INSERT INTO DEPARTAMENTO VALUES(SEQ_DEPARTAMENTO.NEXTVAL,'DESCARTES DE RESIDUOS');
INSERT INTO DEPARTAMENTO VALUES(SEQ_DEPARTAMENTO.NEXTVAL,'BIOSEGURANÇA');

 
INSERT INTO PLANO_DE_SAUDE VALUES(SEQ_PLANO.NEXTVAL, 'GOLDEN_CROSS');
INSERT INTO PLANO_DE_SAUDE VALUES(SEQ_PLANO.NEXTVAL, 'AMIL');
INSERT INTO PLANO_DE_SAUDE VALUES(SEQ_PLANO.NEXTVAL, 'UNIMED');
INSERT INTO PLANO_DE_SAUDE VALUES(SEQ_PLANO.NEXTVAL, 'NOTREDAME');
INSERT INTO PLANO_DE_SAUDE VALUES(SEQ_PLANO.NEXTVAL, 'GAMA');
INSERT INTO PLANO_DE_SAUDE VALUES(SEQ_PLANO.NEXTVAL, 'SMILES');
INSERT INTO PLANO_DE_SAUDE VALUES(SEQ_PLANO.NEXTVAL, 'BRADESCO');
INSERT INTO PLANO_DE_SAUDE VALUES(SEQ_PLANO.NEXTVAL, 'CAIXA_SAUDE');
INSERT INTO PLANO_DE_SAUDE VALUES(SEQ_PLANO.NEXTVAL, 'NEXT_SAUDE');
INSERT INTO PLANO_DE_SAUDE VALUES(SEQ_PLANO.NEXTVAL, 'PLENA_SAUDE');
INSERT INTO PLANO_DE_SAUDE VALUES(SEQ_PLANO.NEXTVAL, 'BLUE_MED');
INSERT INTO PLANO_DE_SAUDE VALUES(SEQ_PLANO.NEXTVAL, 'BIOVIDA_SAUDE');
INSERT INTO PLANO_DE_SAUDE VALUES(SEQ_PLANO.NEXTVAL, 'ALLIANZ_SAUDE');
INSERT INTO PLANO_DE_SAUDE VALUES(SEQ_PLANO.NEXTVAL, 'PORTO_SEGURO_SAUDE');
INSERT INTO PLANO_DE_SAUDE VALUES(SEQ_PLANO.NEXTVAL, 'PREVENT_SENIOR');
INSERT INTO PLANO_DE_SAUDE VALUES(SEQ_PLANO.NEXTVAL, 'INTERCLINICAS');
INSERT INTO PLANO_DE_SAUDE VALUES(SEQ_PLANO.NEXTVAL, 'SANTA_HELENA_SAUDE');
INSERT INTO PLANO_DE_SAUDE VALUES(SEQ_PLANO.NEXTVAL, 'SAO_MIGUEL_SAUDE');
INSERT INTO PLANO_DE_SAUDE VALUES(SEQ_PLANO.NEXTVAL, 'MED_TOUR_SAUDE');
INSERT INTO PLANO_DE_SAUDE VALUES(SEQ_PLANO.NEXTVAL, 'AMEPLAN_SAUDE');

INSERT INTO ENDERECO VALUES (SEQ_ENDERECO.NEXTVAL, 'Caruaru', 'Pernambuco', 'Universitário', 'Av. Portugal');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECO.NEXTVAL, 'Recife', 'Pernambuco', 'Espinheiro', 'Av. Gov. Agamenon Magalhães');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECO.NEXTVAL, 'São Paulo', 'São Paulo', 'Vila Prudente', 'Rua Orfanato');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECO.NEXTVAL, 'Rio de Janeiro', 'Rio de Janeiro', 'Centro', 'Av. Passos');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECO.NEXTVAL, 'Niterói', 'Rio de Janeiro', 'Ingá', 'Rua Sebastião');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECO.NEXTVAL, 'Gravatá', 'Pernambuco', 'Prado', 'R. Joaquim Souto');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECO.NEXTVAL, 'Vitória St. Antão', 'Pernambuco', 'Matriz', 'R. Ismael de Andrade');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECO.NEXTVAL, 'Recife', 'Penambuco', 'Madalena', 'R. Altinho');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECO.NEXTVAL, 'Recife', 'Pernambuco', 'Boa Viagem', 'Av. Conselheiro Aguiar');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECO.NEXTVAL, 'Caruaru', 'Pernambuco', 'Maurício de Nassau', 'R. da Penha');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECO.NEXTVAL, 'Caruaru', 'Pernambuco', 'Universitário', 'Av. Madrid');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECO.NEXTVAL, 'Caruaru', 'Pernambuco', 'Salgado', 'R. Kansas');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECO.NEXTVAL, 'Jab. dos Guararapes', 'Pernambuco', 'Piedade', 'Av. Ayrton Senna da Silva');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECO.NEXTVAL, 'Recife', 'Pernambuco', 'Pina', 'R. Souto Filho');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECO.NEXTVAL, 'Olinda', 'Pernambuco', 'Bairro Novo', 'R. Maria Ramos');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECO.NEXTVAL, 'Olinda', 'Pernambuco', 'Jardim Atlântico', 'R. Olávo Bilac');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECO.NEXTVAL, 'Olinda', 'Pernambuco', 'Bairro Novo', 'R. Maria Ramos');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECO.NEXTVAL, 'Olinda', 'Pernambuco', 'Fragoso', 'R. Cordeiro');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECO.NEXTVAL, 'João Pessoa', 'Paraíba', 'Miramar', 'R. José Liberato');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECO.NEXTVAL, 'João Pessoa', 'Paraíba', 'São José', 'R. Edmundo Filho');

INSERT INTO PACIENTE VALUES(SEQ_PACIENTE.NEXTVAL, 'José Barros Rocha',70,'Masculino',NULL,1);
INSERT INTO PACIENTE VALUES(SEQ_PACIENTE.NEXTVAL, 'Caio Barros Gomes',32,'Masculino',5,10);
INSERT INTO PACIENTE VALUES(SEQ_PACIENTE.NEXTVAL, 'Breno Lima Goncalves',25,'Masculino',8,13);
INSERT INTO PACIENTE VALUES(SEQ_PACIENTE.NEXTVAL, 'Vinicius Ferreira Alves',35,'Masculino',2,20);
INSERT INTO PACIENTE VALUES(SEQ_PACIENTE.NEXTVAL, 'Bianca Cavalcanti Azevedo',82,'Feminino',14,3);
INSERT INTO PACIENTE VALUES(SEQ_PACIENTE.NEXTVAL, 'Carolina Almeida Oliveira',35,'Feminino',19,4);
INSERT INTO PACIENTE VALUES(SEQ_PACIENTE.NEXTVAL, 'Mariana Correia Souza',19,'Feminino',12,7);
INSERT INTO PACIENTE VALUES(SEQ_PACIENTE.NEXTVAL, 'Luana Gomes Sousa',30,'Feminino',17,5);
INSERT INTO PACIENTE VALUES(SEQ_PACIENTE.NEXTVAL, 'Daniel Lima Costa',40,'Masculino',3,6);
INSERT INTO PACIENTE VALUES(SEQ_PACIENTE.NEXTVAL, 'Matilde Alves Correia',60,'Feminino',NULL,9);
INSERT INTO PACIENTE VALUES(SEQ_PACIENTE.NEXTVAL, 'Nicolash Santos Lima',45,'Masculino',NULL,11);
INSERT INTO PACIENTE VALUES(SEQ_PACIENTE.NEXTVAL, 'Gabrielle Azevedo Rodrigues',25,'Feminino',11,12);
INSERT INTO PACIENTE VALUES(SEQ_PACIENTE.NEXTVAL, 'Vitor Ribeiro Cunha',19,'Masculino',2,17);
INSERT INTO PACIENTE VALUES(SEQ_PACIENTE.NEXTVAL, 'Nicole Pinto Oliveira',29,'Feminino',6,18);
INSERT INTO PACIENTE VALUES(SEQ_PACIENTE.NEXTVAL, 'Paulo Goncalves Ferreira',18,'Masculino',7,19);
INSERT INTO PACIENTE VALUES(SEQ_PACIENTE.NEXTVAL, 'Isabela Cavalcanti Rocha',23,'Feminino',18,8);
INSERT INTO PACIENTE VALUES(SEQ_PACIENTE.NEXTVAL, 'Kaua Azevedo Gomes',60,'Masculino',15,2);
INSERT INTO PACIENTE VALUES(SEQ_PACIENTE.NEXTVAL, 'Emilly Costa Melo',27,'Feminino',13,15);
INSERT INTO PACIENTE VALUES(SEQ_PACIENTE.NEXTVAL, 'Marcos Lima Cardoso',80,'Masculino',9,16);
INSERT INTO PACIENTE VALUES(SEQ_PACIENTE.NEXTVAL, 'Evelyn Costa Dias',64,'Feminino',16,14);

INSERT INTO MEDICO VALUES(SEQ_MEDICO.NEXTVAL, 'Tiago Dias Barbosa');
INSERT INTO MEDICO VALUES(SEQ_MEDICO.NEXTVAL, 'Julian Ribeiro Cavalcanti');
INSERT INTO MEDICO VALUES(SEQ_MEDICO.NEXTVAL, 'Livia Pinto Barros');
INSERT INTO MEDICO VALUES(SEQ_MEDICO.NEXTVAL, 'Gabriela Ribeiro Pinto');
INSERT INTO MEDICO VALUES(SEQ_MEDICO.NEXTVAL, 'Luis Pinto Gomes');
INSERT INTO MEDICO VALUES(SEQ_MEDICO.NEXTVAL, 'Estevan Martins Pereira');
INSERT INTO MEDICO VALUES(SEQ_MEDICO.NEXTVAL, 'Isabela Fernandes Correia');
INSERT INTO MEDICO VALUES(SEQ_MEDICO.NEXTVAL, 'Yasmin Castro Lima');
INSERT INTO MEDICO VALUES(SEQ_MEDICO.NEXTVAL, 'Fernanda Araujo Cavalcanti');
INSERT INTO MEDICO VALUES(SEQ_MEDICO.NEXTVAL, 'José Sousa Fernandes');
INSERT INTO MEDICO VALUES(SEQ_MEDICO.NEXTVAL, 'Vitor Gomes Azevedo');
INSERT INTO MEDICO VALUES(SEQ_MEDICO.NEXTVAL, 'Leonardo Gomes Santos');
INSERT INTO MEDICO VALUES(SEQ_MEDICO.NEXTVAL, 'Júlia Correia Gomes');
INSERT INTO MEDICO VALUES(SEQ_MEDICO.NEXTVAL, 'Anna Rocha Souza');
INSERT INTO MEDICO VALUES(SEQ_MEDICO.NEXTVAL, 'Emily Pereira Barbosa');
INSERT INTO MEDICO VALUES(SEQ_MEDICO.NEXTVAL, 'Giovanna Barbosa Barros');
INSERT INTO MEDICO VALUES(SEQ_MEDICO.NEXTVAL, 'Erick Araujo Santos');
INSERT INTO MEDICO VALUES(SEQ_MEDICO.NEXTVAL, 'André Barros Martins');
INSERT INTO MEDICO VALUES(SEQ_MEDICO.NEXTVAL, 'Ryan Araujo Carvalho');
INSERT INTO MEDICO VALUES(SEQ_MEDICO.NEXTVAL, 'Giovanna Cunha Pereira');

INSERT INTO EXAME VALUES(SEQ_EXAME.NEXTVAL,'Glicose',6.00,220330740,200);
INSERT INTO EXAME VALUES(SEQ_EXAME.NEXTVAL,'Hemograma',16.40,220330740,200);
INSERT INTO EXAME VALUES(SEQ_EXAME.NEXTVAL,'Colesterol',6.45,220330740,200);
INSERT INTO EXAME VALUES(SEQ_EXAME.NEXTVAL,'Psa Total',16.45,220330840,260);
INSERT INTO EXAME VALUES(SEQ_EXAME.NEXTVAL,'Exame de Gravidez',25,220331140,300);
INSERT INTO EXAME VALUES(SEQ_EXAME.NEXTVAL,'Hemoglobina Glicada Fração A1c',18.45,220330940,280);
INSERT INTO EXAME VALUES(SEQ_EXAME.NEXTVAL,'TGO – Transaminase Glutâmica Oxalacética',8.45,220331340,360);
INSERT INTO EXAME VALUES(SEQ_EXAME.NEXTVAL,'TGP – Transaminase Glutâmico Pirúvica',6.45,220331340,360);
INSERT INTO EXAME VALUES(SEQ_EXAME.NEXTVAL,'Triglicérides, Soro',5.45,220331640,320);
INSERT INTO EXAME VALUES(SEQ_EXAME.NEXTVAL,'TSH – Hormônio Tireoestimulante',200.45,220331740,340);
INSERT INTO EXAME VALUES(SEQ_EXAME.NEXTVAL,'Vitamina D-25 Hidroxi',70.45,220331740,340);
INSERT INTO EXAME VALUES(SEQ_EXAME.NEXTVAL,'Desoxicortisol',160.45,220332140,300);
INSERT INTO EXAME VALUES(SEQ_EXAME.NEXTVAL,'Hidroxipregnenolona, Soro',640.45,220332240,260);
INSERT INTO EXAME VALUES(SEQ_EXAME.NEXTVAL,'Hidroxicorticosteróides Fracionados, Urina',800.45,220332340,260);
INSERT INTO EXAME VALUES(SEQ_EXAME.NEXTVAL,'Ácido Fólico / Folato – Vitamina B9',16.45,220332440,280);
INSERT INTO EXAME VALUES(SEQ_EXAME.NEXTVAL,'Ácido Fórmico, Urina',36.45,220332540,260);
INSERT INTO EXAME VALUES(SEQ_EXAME.NEXTVAL,'Ácido Hipúrico, Final de Jornada',16.45,220330840,260);
INSERT INTO EXAME VALUES(SEQ_EXAME.NEXTVAL,'Ácido Oxálico Oxalato, Soro',160.45,220332640,400);
INSERT INTO EXAME VALUES(SEQ_EXAME.NEXTVAL,'Ácido Úrico, Urina 24h',6.45,220332640,400);
INSERT INTO EXAME VALUES(SEQ_EXAME.NEXTVAL,'Adenovírus Antígeno, Fezes',46.45,220332640,400);

INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Eduarda Costa', 45, 'Feminino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Mariana Pereira', 31, 'Feminino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Vitória Souza Ribeiro', 35, 'Feminino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Luiz Ribeiro', 43, 'Masculino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Danilo Rocha', 33, 'Masculino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Lavinia Rodrigues', 40, 'Feminino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Caio Sousa Fernandes', 41, 'Masculino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Luís Almeida', 41, 'Masculino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Giovana Souza', 44, 'Feminino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'André Fernandes', 28, 'Masculino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Marina Barbosa', 46, 'Feminino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Luís Melo Rodrigues', 26, 'Masculino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Luis Cavalcanti', 35, 'Masculino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Sophia Cavalcanti', 33, 'Feminino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Murilo Rodrigues', 43, 'Masculino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Thiago Silva', 42, 'Masculino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Maria Cardoso', 31, 'Feminino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Kauê Oliveira Santos', 42, 'Feminino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Manuela Goncalves', 44, 'Feminino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Ryan Rocha', 39, 'Masculino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Bruna Alves', 42, 'Feminino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Vitoria Souza Alves', 48, 'Feminino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Leonor Barros', 32, 'Feminino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Marina Almeida', 39, 'Feminino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Sofia Castro', 30, 'Feminino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Júlio Melo', 30, 'Masculino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Nicole Melo', 43, 'Feminino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Fábio Melo Barros', 39, 'Masculino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Vitoria Alves', 30, 'Feminino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Júlio Castro', 40, 'Masculino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Melissa Araujo Lima', 41, 'Feminino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Otávio Oliveira', 25, 'Masculino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Daniel Azevedo', 43, 'Masculino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Luana Carvalho Azevedo', 28, 'Feminino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Luis Barbosa', 37, 'Masculino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Breno Ribeiro', 45, 'Masculino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Brenda Santos', 30, 'Feminino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Vinícius Cardoso Barbosa', 26, 'Masculino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Julieta Santos', 46, 'Feminino');
INSERT INTO FUNCIONARIO VALUES(SEQ_FUNCIONARIO.NEXTVAL, 'Yasmin Lima', 44, 'Feminino');

INSERT INTO ADMINISTRATIVO VALUES(SEQ_FUNC_ADM.NEXTVAL, 53);
INSERT INTO ADMINISTRATIVO VALUES(SEQ_FUNC_ADM.NEXTVAL, 64);
INSERT INTO ADMINISTRATIVO VALUES(SEQ_FUNC_ADM.NEXTVAL, 67);
INSERT INTO ADMINISTRATIVO VALUES(SEQ_FUNC_ADM.NEXTVAL, 82);
INSERT INTO ADMINISTRATIVO VALUES(SEQ_FUNC_ADM.NEXTVAL, 73);
INSERT INTO ADMINISTRATIVO VALUES(SEQ_FUNC_ADM.NEXTVAL, 42);
INSERT INTO ADMINISTRATIVO VALUES(SEQ_FUNC_ADM.NEXTVAL, 50);
INSERT INTO ADMINISTRATIVO VALUES(SEQ_FUNC_ADM.NEXTVAL, 48);
INSERT INTO ADMINISTRATIVO VALUES(SEQ_FUNC_ADM.NEXTVAL, 48);
INSERT INTO ADMINISTRATIVO VALUES(SEQ_FUNC_ADM.NEXTVAL, 32);
INSERT INTO ADMINISTRATIVO VALUES(SEQ_FUNC_ADM.NEXTVAL, 98);
INSERT INTO ADMINISTRATIVO VALUES(SEQ_FUNC_ADM.NEXTVAL, 78);
INSERT INTO ADMINISTRATIVO VALUES(SEQ_FUNC_ADM.NEXTVAL, 78);
INSERT INTO ADMINISTRATIVO VALUES(SEQ_FUNC_ADM.NEXTVAL, 76);
INSERT INTO ADMINISTRATIVO VALUES(SEQ_FUNC_ADM.NEXTVAL, 67);
INSERT INTO ADMINISTRATIVO VALUES(SEQ_FUNC_ADM.NEXTVAL, 64);
INSERT INTO ADMINISTRATIVO VALUES(SEQ_FUNC_ADM.NEXTVAL, 53);
INSERT INTO ADMINISTRATIVO VALUES(SEQ_FUNC_ADM.NEXTVAL, 66);
INSERT INTO ADMINISTRATIVO VALUES(SEQ_FUNC_ADM.NEXTVAL, 55);
INSERT INTO ADMINISTRATIVO VALUES(SEQ_FUNC_ADM.NEXTVAL, 69);


INSERT INTO TECNICO VALUES(SEQ_FUNC_TEC.NEXTVAL,'Enfermeiro', 27);
INSERT INTO TECNICO VALUES(SEQ_FUNC_TEC.NEXTVAL,'Enfermeiro', 27);
INSERT INTO TECNICO VALUES(SEQ_FUNC_TEC.NEXTVAL,'Enfermeiro', 32);
INSERT INTO TECNICO VALUES(SEQ_FUNC_TEC.NEXTVAL,'Enfermeiro', 32);
INSERT INTO TECNICO VALUES(SEQ_FUNC_TEC.NEXTVAL,'Enfermeiro', 27);
INSERT INTO TECNICO VALUES(SEQ_FUNC_TEC.NEXTVAL,'Biomédico', 24);
INSERT INTO TECNICO VALUES(SEQ_FUNC_TEC.NEXTVAL,'Biomédico', 25);
INSERT INTO TECNICO VALUES(SEQ_FUNC_TEC.NEXTVAL,'Biomédico', 25);
INSERT INTO TECNICO VALUES(SEQ_FUNC_TEC.NEXTVAL,'Contador', 29);
INSERT INTO TECNICO VALUES(SEQ_FUNC_TEC.NEXTVAL,'Contador', 29);
INSERT INTO TECNICO VALUES(SEQ_FUNC_TEC.NEXTVAL,'T.I', 22);
INSERT INTO TECNICO VALUES(SEQ_FUNC_TEC.NEXTVAL,'T.I', 22);
INSERT INTO TECNICO VALUES(SEQ_FUNC_TEC.NEXTVAL, NULL , 28);
INSERT INTO TECNICO VALUES(SEQ_FUNC_TEC.NEXTVAL, NULL , 28);
INSERT INTO TECNICO VALUES(SEQ_FUNC_TEC.NEXTVAL, NULL , 31);
INSERT INTO TECNICO VALUES(SEQ_FUNC_TEC.NEXTVAL, NULL , 30);
INSERT INTO TECNICO VALUES(SEQ_FUNC_TEC.NEXTVAL, NULL , 31);
INSERT INTO TECNICO VALUES(SEQ_FUNC_TEC.NEXTVAL, NULL , 30);
INSERT INTO TECNICO VALUES(SEQ_FUNC_TEC.NEXTVAL,'Bioquímico', 26);
INSERT INTO TECNICO VALUES(SEQ_FUNC_TEC.NEXTVAL,'Bioquímico', 26);